# Generated by Django 6.0.7 on 2026-08-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_plant_myplant'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='page_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
