# Generated by Django 6.0.7 on 2026-08-05 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disease_name', models.CharField(max_length=200, unique=True)),
                ('plant_name', models.CharField(max_length=100)),
                ('symptoms', models.TextField()),
                ('causes', models.TextField()),
                ('treatment', models.TextField()),
                ('prevention', models.TextField()),
            ],
        ),
    ]
