# Generated by Django 6.0.7 on 2026-08-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_scanhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanhistory',
            name='plant_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanhistory',
            name='image',
            field=models.ImageField(upload_to='scans/'),
        ),
    ]
